/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginPatientRouteImport } from './routes/login.patient'
import { Route as LoginDoctorRouteImport } from './routes/login.doctor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPatientRoute = LoginPatientRouteImport.update({
  id: '/login/patient',
  path: '/login/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDoctorRoute = LoginDoctorRouteImport.update({
  id: '/login/doctor',
  path: '/login/doctor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/doctor': typeof LoginDoctorRoute
  '/login/patient': typeof LoginPatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/doctor': typeof LoginDoctorRoute
  '/login/patient': typeof LoginPatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/doctor': typeof LoginDoctorRoute
  '/login/patient': typeof LoginPatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/doctor' | '/login/patient'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/doctor' | '/login/patient'
  id: '__root__' | '/' | '/login/doctor' | '/login/patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginDoctorRoute: typeof LoginDoctorRoute
  LoginPatientRoute: typeof LoginPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/patient': {
      id: '/login/patient'
      path: '/login/patient'
      fullPath: '/login/patient'
      preLoaderRoute: typeof LoginPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/doctor': {
      id: '/login/doctor'
      path: '/login/doctor'
      fullPath: '/login/doctor'
      preLoaderRoute: typeof LoginDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginDoctorRoute: LoginDoctorRoute,
  LoginPatientRoute: LoginPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
